In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os

print(os.listdir('/content/drive/MyDrive/ECERC'))

['data', 'models', 'results']


In [ ]:
print(os.path.exists('/content/drive/MyDrive/ECERC/data/meld'))
print(os.path.exists('/content/drive/MyDrive/ECERC/models/MELD'))

True
True


In [ ]:
!git clone https://github.com/TAN-OpenLab/ECERC.git /content/ECERC

Cloning into '/content/ECERC'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 28 (delta 2), reused 3 (delta 1), pack-reused 19 (from 1)
Receiving objects: 100% (28/28), 44.70 MiB | 34.21 MiB/s, done.
Resolving deltas: 100% (8/8), done.


In [ ]:
import os

print(os.listdir('/content/ECERC'))

['requirement.yml', '.git', 'IEMOCAP', 'MELD', 'OS_info.txt', 'README.md']


In [ ]:
print(os.path.exists('/content/ECERC/IEMOCAP'))
print(os.path.exists('/content/ECERC/MELD'))
print(os.path.exists('/content/ECERC/README.md'))
print(os.path.exists('/content/ECERC/requirement.yml'))

True
True
True
True


In [ ]:
import shutil

shutil.copy(
    '/content/drive/MyDrive/ECERC/models/MELD/ECERC_MODEL.pkl',
    '/content/ECERC/MELD/ECERC_MODEL.pkl'
)

'/content/ECERC/MELD/ECERC_MODEL.pkl'

In [ ]:
import os

print(os.path.exists('/content/ECERC/MELD/ECERC_MODEL.pkl'))

True


In [ ]:
import os

print(os.path.getsize('/content/ECERC/MELD/ECERC_MODEL.pkl'))

24613444


In [ ]:
import sys
import torch

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
PyTorch: 2.11.0+cu130
CUDA available: True
GPU: Tesla T4


In [ ]:
!pip install -q numpy pandas scikit-learn

In [ ]:
import numpy
import pandas
import sklearn
import torch

print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("Scikit-learn:", sklearn.__version__)
print("PyTorch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

NumPy: 2.1.3
Pandas: 2.2.3
Scikit-learn: 1.6.1
PyTorch: 2.11.0+cu130
CUDA: True


In [ ]:
import os

os.makedirs('/content/ECERC/data/meld', exist_ok=True)

In [ ]:
import shutil

shutil.copy(
    '/content/drive/MyDrive/ECERC/data/meld/meld_emotion_semantic_features_roberta.pkl',
    '/content/ECERC/data/meld/meld_emotion_semantic_features_roberta.pkl'
)

'/content/ECERC/data/meld/meld_emotion_semantic_features_roberta.pkl'

In [ ]:
import os

path = '/content/ECERC/data/meld/meld_emotion_semantic_features_roberta.pkl'

print("Exists:", os.path.exists(path))
print("Size:", os.path.getsize(path), "bytes")

Exists: True
Size: 509327864 bytes


In [ ]:
import os

model_path = '/content/ECERC/MELD/ECERC_MODEL.pkl'

print("Exists:", os.path.exists(model_path))
print("Size:", os.path.getsize(model_path), "bytes")

Exists: True
Size: 24613444 bytes


In [ ]:
import os

paths = [
    '/content/ECERC/IEMOCAP',
    '/content/ECERC/MELD',
    '/content/ECERC/MELD/inference.py',
    '/content/ECERC/MELD/dataloader.py',
    '/content/ECERC/MELD/model.py',
    '/content/ECERC/MELD/loss.py',
    '/content/ECERC/MELD/ECERC_MODEL.pkl',
    '/content/ECERC/data/meld',
    '/content/ECERC/data/meld/meld_emotion_semantic_features_roberta.pkl',
    '/content/ECERC/requirement.yml',
    '/content/ECERC/README.md',
]

for path in paths:
    print("OK   " if os.path.exists(path) else "MISS ", path)

OK    /content/ECERC/IEMOCAP
OK    /content/ECERC/MELD
OK    /content/ECERC/MELD/inference.py
OK    /content/ECERC/MELD/dataloader.py
OK    /content/ECERC/MELD/model.py
OK    /content/ECERC/MELD/loss.py
OK    /content/ECERC/MELD/ECERC_MODEL.pkl
OK    /content/ECERC/data/meld
OK    /content/ECERC/data/meld/meld_emotion_semantic_features_roberta.pkl
OK    /content/ECERC/requirement.yml
OK    /content/ECERC/README.md


In [ ]:
%cd /content/ECERC/MELD

/content/ECERC/MELD


In [ ]:
import os

print(os.getcwd())

/content/ECERC/MELD


In [ ]:
!python inference.py

Running on GPU
The model have 5810187 paramerters in total
Running on the multi features........
test_loss: 0.7238, test_acc: 67.55, test_fscore: 66.58, time: 0.96 sec
              precision    recall  f1-score   support

         neu     0.7672    0.8344    0.7994      1256
         sur     0.5680    0.5943    0.5809       281
         fea     0.3750    0.2400    0.2927        50
         sad     0.5308    0.3317    0.4083       208
         joy     0.6543    0.6592    0.6568       402
         dis     0.4474    0.2500    0.3208        68
         ang     0.5362    0.5362    0.5362       345

    accuracy                         0.6755      2610
   macro avg     0.5541    0.4923    0.5136      2610
weighted avg     0.6632    0.6755    0.6658      2610

[[1048   42    5   33   68    4   56]
 [  44  167    2    3   33    2   30]
 [  16    7   12    5    2    1    7]
 [  75   14    7   69   10    3   30]
 [  82   25    2    6  265    2   20]
 [  25    4    1    4    0   17   17]
 [  76 

In [ ]:
import os

os.makedirs('/content/drive/MyDrive/ECERC/results', exist_ok=True)

In [ ]:
!python inference.py 2>&1 | tee /content/drive/MyDrive/ECERC/results/meld_baseline_output.txt

Running on GPU
The model have 5810187 paramerters in total
Running on the multi features........
test_loss: 0.7238, test_acc: 67.55, test_fscore: 66.58, time: 0.53 sec
              precision    recall  f1-score   support

         neu     0.7672    0.8344    0.7994      1256
         sur     0.5680    0.5943    0.5809       281
         fea     0.3750    0.2400    0.2927        50
         sad     0.5308    0.3317    0.4083       208
         joy     0.6543    0.6592    0.6568       402
         dis     0.4474    0.2500    0.3208        68
         ang     0.5362    0.5362    0.5362       345

    accuracy                         0.6755      2610
   macro avg     0.5541    0.4923    0.5136      2610
weighted avg     0.6632    0.6755    0.6658      2610

[[1048   42    5   33   68    4   56]
 [  44  167    2    3   33    2   30]
 [  16    7   12    5    2    1    7]
 [  75   14    7   69   10    3   30]
 [  82   25    2    6  265    2   20]
 [  25    4    1    4    0   17   17]
 [  76 

In [ ]:
print(open('/content/drive/MyDrive/ECERC/results/meld_baseline_output.txt').read())

Running on GPU
The model have 5810187 paramerters in total
Running on the multi features........
test_loss: 0.7238, test_acc: 67.55, test_fscore: 66.58, time: 0.53 sec
              precision    recall  f1-score   support

         neu     0.7672    0.8344    0.7994      1256
         sur     0.5680    0.5943    0.5809       281
         fea     0.3750    0.2400    0.2927        50
         sad     0.5308    0.3317    0.4083       208
         joy     0.6543    0.6592    0.6568       402
         dis     0.4474    0.2500    0.3208        68
         ang     0.5362    0.5362    0.5362       345

    accuracy                         0.6755      2610
   macro avg     0.5541    0.4923    0.5136      2610
weighted avg     0.6632    0.6755    0.6658      2610

[[1048   42    5   33   68    4   56]
 [  44  167    2    3   33    2   30]
 [  16    7   12    5    2    1    7]
 [  75   14    7   69   10    3   30]
 [  82   25    2    6  265    2   20]
 [  25    4    1    4    0   17   17]
 [  76 

In [ ]:
import torch
print(torch.cuda.get_device_name(0))

Tesla T4


In [ ]:
baseline_summary = """ECERC MELD Baseline
====================

Dataset: MELD
Model: ECERC_MODEL.pkl
Features: Authors' preprocessed multimodal features
Evaluation: Official inference.py
GPU: Tesla T4

Accuracy: 67.55
Weighted F1: 66.58

Per-class F1:
Neutral: 79.94
Surprise: 58.09
Fear: 29.27
Sadness: 40.83
Joy: 65.68
Disgust: 32.08
Anger: 53.62

Reference paper/SOP values:
Accuracy: 67.32
Weighted F1: 66.46

Notes:
The reference values are reported in the project SOP. The paper reports results averaged over 3 runs.
"""

with open('/content/drive/MyDrive/ECERC/results/meld_baseline_summary.txt', 'w') as f:
    f.write(baseline_summary)

In [ ]:
raw_output = """Running on GPU
The model have 5810187 paramerters in total
Running on the multi features........
test_loss: 0.7238, test_acc: 67.55, test_fscore: 66.58, time: 0.53 sec
              precision    recall  f1-score   support

         neu     0.7672    0.8344    0.7994      1256
         sur     0.5680    0.5943    0.5809       281
         fea     0.3750    0.2400    0.2927        50
         sad     0.5308    0.3317    0.4083       208
         joy     0.6543    0.6592    0.6568       402
         dis     0.4474    0.2500    0.3208        68
         ang     0.5362    0.5362    0.5362       345

    accuracy                         0.6755      2610
   macro avg     0.5541    0.4923    0.5136      2610
weighted avg     0.6632    0.6755    0.6658      2610

[[1048   42    5   33   68    4   56]
 [  44  167    2    3   33    2   30]
 [  16    7   12    5    2    1    7]
 [  75   14    7   69   10    3   30]
 [  82   25    2    6  265    2   20]
 [  25    4    1    4    0   17   17]
 [  76    35    3   10   27    9  185]]
"""

with open('/content/drive/MyDrive/ECERC/results/meld_baseline_output.txt', 'w') as f:
    f.write(raw_output)